### ISSUE TITLE
Assigned Functions Do Not Work

### ISSUE THREAD

**Issue by lswee** [devbobo/homebridge-flic#14]
Hey, I've gone through the ringer today re-setting up my homebridge from scratch. Everything works as it used to... except my Flics.

The Flics are in my Home app.

When I click them, home bridge knows that's happened:
[2018-8-4 20:20:59] [Flic] 80e4da73b7f6 - ButtonSingleClick
and within the Home app it pulses to show that it's been clicked.

However, even though an action has been assigned to the single click, it doesn't do that action.

If I go into the settings for the single click/action and tap 'test action' the light turns on as expected.

Where could the issue be?

**Comment by lswee** [comment]
I mentioned in the other thread that Hesperus says it "times out" when I add a new button, but from that point everything works (registered by homebridge and within Home app) except for it's assigned function.

Could the timeout thing be causing an issue?

Here's the log:
[2018-8-4 20:46:27] [Flic] Controller [localhost:5551] - Scanner removed
[2018-8-4 20:46:27] [Flic] Found a public button. Now connecting...
[2018-8-4 20:46:27] [Flic] Found: Flic 73b7f3 (80e4da73b7f3)
[2018-8-4 20:46:27] [Flic] Controller [localhost:5551] - Scanner failed: Timed out
[2018-8-4 20:46:28] [Flic] 80e4da73b7f3 - Disconnected TimedOut
[2018-8-4 20:46:28] [Flic] 80e4da73b7f3 - Disconnected TimedOut
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/pi/.homebridge/config.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Server._handleNewConfig (/usr/lib/node_modules/homebridge/lib/server.js:626:6)
    at emitMany (events.js:147:13)
    at BridgeSetupManager.emit (events.js:224:7)
    at BridgeSetupManager.<anonymous> (/usr/lib/node_modules/homebridge/lib/bridgeSetupManager.js:83:12)
    at emitMany (events.js:147:13)
    at BridgeSetupSession.emit (events.js:224:7)
    at BridgeSetupSession.pluginResponseHandler (/usr/lib/node_modules/homebridge/lib/bridgeSetupSession.js:98:10)
    at FlicPlatform.configurationRequestHandler (/usr/lib/node_modules/homebridge-flic/index.js:294:17)

**Comment by lswee** [comment]
I managed to get this working in the end. I _think_ it was a problem with the AppleTV not relaying the message, but I’m not sure...

**Comment by hellomarb** [comment]
I have the same issue. How you got this working?
Restarting Apple TV or the pi didn't help, but the actions are triggered in homebridge ...

**Comment by lswee** [comment]
I think I had to reset (more than restart) the AppleTV, which isn’t an ideal solution.

**Comment by hellomarb** [comment]
For all other searching this issue: it is homekit syncing on the other devices.
After 15 min I was able to control it over the home app. 
Restarting the devices didn't triggered a sync, it took some time.
